version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistics-app-backend
    ports: 
      - "3000:3000"
    depends_on:
      - redis_server

  redis_server:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"